from operator import mul
from re import sub


products = [
    {"name": "Laptop", "price": 60000, "stock": 5},
    {"name": "Smartphone", "price": 30000, "stock": 10},
    {"name": "Tablet", "price": 20000, "stock": 7}
]

# ✏️ Hints:
# Use loops (for loop).

# Update the "stock" field manually.

# Track sold quantity to calculate revenue.

# Check stock using if stock < 3.


# Print a nice list of all products:
# ➔ Example:
# Product: Laptop | Price: 60000 | Stock: 5
for product in products:
    print(f"{product["name"]}| {product["price"]}| {product["stock"]}")
# Sell 2 Smartphones and 1 Tablet.
# ➔ Decrease their stock accordingly.
quantity_sold_samrtphome = 2
quantity_sold_tablets = 1 
products[1].update({"stock" : 8})
products[2].update({"stock" : 6})
# Print the updated stock for each product.
print(products)
# Calculate and print the total revenue made from these sales.
# (💡 Revenue = price × quantity sold)
rev_smartphone = mul(products[1]["price"], quantity_sold_samrtphome)
print(rev_smartphone)
rev_tablet = mul(products[2]["price"], quantity_sold_tablets)
print(rev_tablet)

revenue = rev_smartphone + rev_tablet
print(f"the total revenue generated by the sales is : {revenue}")
# If any product's stock becomes less than 3, print a warning:
# ➔ Example: "Warning: Stock of Laptop is low!"

# updating a value of stock manually:-
products[0].update({"stock" : 2})
for product in products:
    if product["stock"] < 3 :
        print(f"Warning: Stock of {product['name']} is low!")
